title: "Abimbola Ojikutu"
email: fellowship@mlh.io
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" 
url: "/abimbola.github.io" 
twitter_username: jummyoh
github_username:  abimbola-ai

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
